# -*- coding: utf-8 -*-
"""Layer freezing, fine-tuning on Region B dataset, comparative benchmarking.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_maFAN5e_N9sSWaFUGcH1WsMSSyb7E0m
"""

#Base Model Architecture & Pre-Training (Region A)

import tensorflow as tf
from tensorflow.keras import layers, models

# 1. Load your pre-trained model trained on Region A
base_model = tf.keras.models.load_model('model_region_A.keras')

# Display architecture summary
base_model.summary()

#Data Preprocessing & Sequence Preparation

import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

# Define features and target variable
FEATURES = [
    'DC_POWER', 'AMBIENT_TEMPERATURE', 'MODULE_TEMPERATURE', 'IRRADIATION',
    'hour', 'minute', 'day_of_week', 'day_of_year', 'month',
    'hour_sin', 'hour_cos', 'day_sin', 'day_cos'
]
TARGET = 'AC_POWER'
SEQUENCE_LENGTH = 4  # 4 time-steps (e.g., 1 hour of 15-min intervals)

def load_and_create_sequences(train_path, val_path, test_path, seq_len=SEQUENCE_LENGTH):
    """Loads CSV sets and constructs 3D sliding window tensors (samples, timesteps, features)."""
    df_train = pd.read_csv(train_path)
    df_val = pd.read_csv(val_path)
    df_test = pd.read_csv(test_path)

    def create_sequences(df, seq_length):
        X, y = [], []
        data_x = df[FEATURES].values
        data_y = df[TARGET].values
        for i in range(len(df) - seq_length):
            X.append(data_x[i : i + seq_length])
            y.append(data_y[i + seq_length])
        return np.array(X), np.array(y)

    X_train, y_train = create_sequences(df_train, seq_len)
    X_val, y_val = create_sequences(df_val, seq_len)
    X_test, y_test = create_sequences(df_test, seq_len)

    return (X_train, y_train), (X_val, y_val), (X_test, y_test)

# Load Region A Datasets
(X_train_A, y_train_A), (X_val_A, y_val_A), (X_test_A, y_test_A) = load_and_create_sequences(
    'train.csv', 'validation.csv', 'test.csv'
)

# Load Region B Datasets
(X_train_B, y_train_B), (X_val_B, y_val_B), (X_test_B, y_test_B) = load_and_create_sequences(
    'train (1).csv', 'validation (1).csv', 'test (1).csv'
)

print(f"Region A Train shape: {X_train_A.shape}, Test shape: {X_test_A.shape}")
print(f"Region B Train shape: {X_train_B.shape}, Test shape: {X_test_B.shape}")

#Build & Pre-train Base Model on Region A

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Input

# 1. Build Base Architecture
base_model = Sequential([
    Input(shape=(SEQUENCE_LENGTH, len(FEATURES))),
    LSTM(64, return_sequences=True, name="lstm_layer_1"),
    Dropout(0.2),
    LSTM(32, return_sequences=False, name="lstm_layer_2"),
    Dropout(0.2),
    Dense(16, activation='relu', name="dense_feature_head"),
    Dense(1, activation='linear', name="output_layer")
], name="Base_Model_Region_A")

base_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=['mae']
)

# 2. Train on Region A
print("\n--- Pre-training Base Model on Region A ---")
base_model.fit(
    X_train_A, y_train_A,
    validation_data=(X_val_A, y_val_A),
    epochs=25,
    batch_size=32,
    verbose=1
)

# Save Region A Base Weights
base_model.save('model_region_A.keras')

#Layer Freezing & Transfer Learning (Region B)

# Load pre-trained Region A model
transfer_model_frozen = tf.keras.models.load_model('model_region_A.keras')

# Freeze feature extraction layers (keep only top classification/regression heads trainable)
for layer in transfer_model_frozen.layers[:-2]:
    layer.trainable = False

transfer_model_frozen.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-4),
    loss='mse',
    metrics=['mae']
)

print("\n--- Training Frozen Feature Extractor on Region B ---")
transfer_model_frozen.fit(
    X_train_B, y_train_B,
    validation_data=(X_val_B, y_val_B),
    epochs=15,
    batch_size=32,
    verbose=1
)

#Fine-Tuning Stage (Unfreezing Upper Layers)

# Clone model for fine-tuning
fine_tune_model = tf.keras.models.load_model('model_region_A.keras')

# Unfreeze upper LSTM layer and Dense layers for subtle weight updates
for layer in fine_tune_model.layers:
    if layer.name in ['lstm_layer_2', 'dense_feature_head', 'output_layer']:
        layer.trainable = True
    else:
        layer.trainable = False

# Recompile with reduced learning rate to prevent exploding/distorting pre-trained features
fine_tune_model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss='mse',
    metrics=['mae']
)

print("\n--- Fine-tuning Unfrozen Model on Region B ---")
fine_tune_model.fit(
    X_train_B, y_train_B,
    validation_data=(X_val_B, y_val_B),
    epochs=20,
    batch_size=32,
    verbose=1
)

#Comparative Benchmarking

# 1. Baseline Model (Trained strictly on Region B from Scratch)
scratch_model_B = tf.keras.models.clone_model(base_model)
scratch_model_B.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
    loss='mse',
    metrics=['mae']
)
scratch_model_B.fit(
    X_train_B, y_train_B,
    validation_data=(X_val_B, y_val_B),
    epochs=25,
    batch_size=32,
    verbose=0
)

# 2. Benchmark Evaluation Function
def evaluate_strategy(model, X_test, y_test, strategy_name):
    preds = model.predict(X_test, verbose=0).flatten()
    rmse = np.sqrt(mean_squared_error(y_test, preds))
    mae = mean_absolute_error(y_test, preds)
    r2 = r2_score(y_test, preds)
    return {
        "Strategy": strategy_name,
        "RMSE": round(rmse, 4),
        "MAE": round(mae, 4),
        "R² Score": round(r2, 4)
    }

# 3. Aggregate Performance Metrics on Region B Test Data (test (1).csv)
results = [
    evaluate_strategy(scratch_model_B, X_test_B, y_test_B, "Scratch Model (Region B Only)"),
    evaluate_strategy(transfer_model_frozen, X_test_B, y_test_B, "Layer Freezing (Feature Extractor)"),
    evaluate_strategy(fine_tune_model, X_test_B, y_test_B, "Fine-Tuned Transfer Model")
]

benchmark_df = pd.DataFrame(results)
print("\n--- Comparative Benchmarking Summary (Region B Test Set) ---")
print(benchmark_df.to_string(index=False))